version: '3'

services:
  db-server:
    image: mysql
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql:/etc/mysql/conf.d
      - ./mysql/music:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=otokake